---
version: '3'
services:
  grlc:
    image: clariah/grlc:latest
    container_name: grlc
    ports:
      - 8088:8088
    environment:
      - DEBUG=true
      - GRLC_GITHUB_ACCESS_TOKEN=xxx
      - GRLC_SERVER_NAME=localhost:8088
      - GRLC_SPARQL_ENDPOINT=http://makingsense.liacs.nl/rdf4j-server/repositories/NC
      - GRLC_LOCAL_SPARQL_DIR=/home/grlc/queries
