#+ summary: Get taxa recorder by an entity (e.g. a person, group or organization).
#+ tags:
#+  - Get taxa recorded by an entity
#+ defaults:
#+  - entity: http://viaf.org/viaf/45106482

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX nhc: <http://makingsense.liacs.nl/rdf/nhc/>
PREFIX nc: <http://testingsense.liacs.nl/rdf/nc#>
PREFIX dwc: <http://rs.tdwg.org/dwc/>
PREFIX dwciri: <http://rs.tdwg.org/dwc/iri/>
PREFIX dsw: <http://purl.org/dsw/>
PREFIX viaf: <http://viaf.org/viaf/>
PREFIX oa: <http://www.w3.org/ns/oa#> 
SELECT DISTINCT ?label ?page WHERE {
       ?taxon rdfs:label ?label .
       ?identification dwciri:toTaxon ?taxon .
       ?identification dsw:isBasedOn ?humanobservation .
       ?annotation oa:hasBody ?humanobservation .
       ?annotation oa:hasTarget ?page .
       ?organism dsw:hasIdentification ?identification . 
       ?occurrence dsw:occurrenceOf ?organism . 
       ?occurrence dwciri:recordedBy ?_entity_iri .
}